/*增加列*/
  ALTER TABLE emp01 ADD eno NUMBER(4);

/*修改列定义*/
  ALTER TABLE emp01 MODIFY job VARCHAR2(15)  DEFAULT 'CLERK';

/*删除列*/
  ALTER TABLE emp01 DROP COLUMN dno;

/*修改列名*/
  ALTER TABLE emp01 RENAME COLUMN eno TO empno;

/*修改表名*/
  RENAME emp01 TO employee;

/*先删除后增加主键*/
ALTER TABLE MQ_PS_PREPARE DROP CONSTRAINT PK_MQ_PS_PREPARE;
ALTER TABLE MQ_PS_PREPARE ADD CONSTRAINT PK_MQ_PS_PREPARE PRIMARY KEY (OID);
/*操作表常用SQL*/
COMMENT ON TABLE TEST1 IS '测试表';--给表填加注释
COMMENT ON COLUMN T_AI_BU_INSURE_ORDER.LINK_NO IS '合同单号';--给列加注释
ALTER TABLE TEST1 MODIFY PLANMONTH NUMBER;
ALTER TABLE TEST1 ADD LONG1 LONG;
ALTER TABLE TEST1 ADD DFD NUMBER(14,2) DEFAULT 0;
ALTER TABLE TEST1 ADD FDFED NUMBER DEFAULT 1;
ALTER TABLE TEST1 ADD CONSTRAINT PK_ID PRIMARY KEY (ID);
ALTER TABLE TEST1 ADD CONSTRAINT FK_D_ID FOREIGN KEY (D_ID) REFERENCES TEST2 (RID);
ALTER TABLE TEST1 ADD CONSTRAINT U_DFD UNIQUE (PLANMONTH);
ALTER TABLE TEST1 DROP COLUMN PLANMONTH;

