//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Breezee.WorkHelper.DBTool.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedPath {
            get {
                return ((string)(this["LastSelectedPath"]));
            }
            set {
                this["LastSelectedPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoEntity_Path {
            get {
                return ((string)(this["AutoEntity_Path"]));
            }
            set {
                this["AutoEntity_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DT_")]
        public string AutoEntity_ClassPre {
            get {
                return ((string)(this["AutoEntity_ClassPre"]));
            }
            set {
                this["AutoEntity_ClassPre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoEntity_ClassEnd {
            get {
                return ((string)(this["AutoEntity_ClassEnd"]));
            }
            set {
                this["AutoEntity_ClassEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EF_")]
        public string AutoEntity_PropertyPre {
            get {
                return ((string)(this["AutoEntity_PropertyPre"]));
            }
            set {
                this["AutoEntity_PropertyPre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExcelCol2Row_FixRowCount {
            get {
                return ((int)(this["ExcelCol2Row_FixRowCount"]));
            }
            set {
                this["ExcelCol2Row_FixRowCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ExcelCol2Row_EachDataRowCount {
            get {
                return ((int)(this["ExcelCol2Row_EachDataRowCount"]));
            }
            set {
                this["ExcelCol2Row_EachDataRowCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClickCopyPath {
            get {
                return ((string)(this["ClickCopyPath"]));
            }
            set {
                this["ClickCopyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelCopyDataConnect {
            get {
                return ((string)(this["ExcelCopyDataConnect"]));
            }
            set {
                this["ExcelCopyDataConnect"] = value;
            }
        }
    }
}
