/*增加自增长序列*/
CREATE OR REPLACE TRIGGER TR_MQSEND_TEMP_RECORDID
BEFORE INSERT ON MQSEND_TEMP
FOR EACH ROW
BEGIN
SELECT SE_MQSEND_TEMP.NEXTVAL INTO :NEW.RECORDID FROM DUAL;
END;

--实现自增长序列的触发器
CREATE OR REPLACE TRIGGER TRG_PK_PS_QJ_SH_BAK
 BEFORE INSERT ON PS_QJ_SH_BAK
 FOR EACH ROW
BEGIN
 SELECT SEQ_PK_PS_QJ_SH_BAK.NEXTVAL INTO :NEW.RECORDNO FROM DUAL;
END;
