/*删除存储过程*/
--1、删除CLR存储过程
IF ( OBJECT_ID('P_P_E3S_OWEQTY_RECEIPT', 'PC') IS NOT NULL ) 
	DROP PROCEDURE [dbo].[P_P_E3S_OWEQTY_RECEIPT] ; 
--2、删除SQL或CLR存储过程
IF ( OBJECT_ID('P_PA_E3S_OUTSTOCK_RECEIPT') IS NOT NULL ) 
	DROP PROCEDURE P_PA_E3S_OUTSTOCK_RECEIPT
--3、删除SQL或CLR存储过程
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[IFR_UC_T_BASE_ASSESSMENT_ITEMProcedure]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[IFR_UC_T_BASE_ASSESSMENT_ITEMProcedure]


