CREATE OR REPLACE VIEW V_PA_PART_SALE_RETURN AS
SELECT A.OUT_RETURN_APPLY_CODE AS OUT_STOCK_ORDER,
       '1' OUT_TYPE,
       A.CUST_ID AS CUST_ID,
       A.CUST_NAME,
       A.CREATED_DATE AS OUT_DATE,
       F_MDS_GET_EMPNAME_BY_USERID(A.CREATOR) AS DUTY_MAN,
       A.OUT_RETURN_AMOUNT AS COST_AMOUNT, --不含税库存成本总价
       A.OUT_RETURN_AMOUNT AS PRICE_AMOUNT, --含税成本金额
       B.LINK_MAN AS LINK_MAN, --目标网点联系人
       B.LINK_TEL AS LINK_TEL, --目标网点联系人电话
       A.RELATE_ORDER_CODE AS SALE_ORDER_CODE,
       A.CREATED_DATE AS MAKE_ORDER_DATE,
       '' AS REMARK,
       DLR.DLR_CODE AS NET_CODE,
       B.SOURCE_DLR_ID,
       DLRS.DLR_CODE AS SOURCE_NET_CODE,
       A.CREATOR,
       A.CREATED_DATE AS INSERT_DATE,
       A.MODIFIER,
       A.LAST_UPDATED_DATE
  FROM T_PA_BU_OUT_RETURN_APPLY A
  LEFT JOIN T_PA_DB_DLR_CUST B ON A.CUST_ID = B.PA_CUST_ID
  LEFT JOIN T_MDM_ORG_DLR DLR ON DLR.DLR_ID = A.DLR_ID
  LEFT JOIN T_MDM_ORG_DLR DLRS ON DLRS.DLR_ID = B.SOURCE_DLR_ID
 WHERE A.OUT_RETURN_TYPE = '103'
   AND A.IS_ENABLE = '1'
   AND A.RETURN_APPLY_BIG_TYPE = '2' /*调拨取消*/
;
