/*FOR循环：整型范围*/
FOR I IN 1 .. LENGTH(P_NAME) LOOP
    V_COMPARE := F_NLSSORT(SUBSTR(P_NAME, I, 1));
    IF V_COMPARE >= F_NLSSORT(' 吖 ') AND V_COMPARE <= F_NLSSORT('骜 ') THEN
      V_RETURN := V_RETURN || 'a';
    ELSIF V_COMPARE >= F_NLSSORT('八 ') AND V_COMPARE <= F_NLSSORT('簿 ') THEN
      V_RETURN := V_RETURN || 'b';
    ELSE
      V_RETURN := V_RETURN || 'z';
    END IF;
END LOOP;

/*FOR循环：查询结果游标*/
FOR DR IN (SELECT M.MAIN_BRAND_CODE,M.HELP_BRAND_CODE,M.ORDER_BRAND_CODE
            FROM T_DB_BRAND_CONFIG M WHERE M.IS_ENABLE = '1'
            AND M.BRAND_CONFIG_ID = V_BRAND_CONFIG_ID) LOOP
    IF NVL(V_RESULT, '-1') = '-1' THEN
        V_RESULT := DR.HELP_BRAND_NAME;
    ELSE
        V_RESULT := V_RESULT || '、' || DR.HELP_BRAND_NAME;
    END IF;
END LOOP;